# Build stage
FROM node:20-slim as build-stage

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Production stage
FROM nginx:stable-alpine as production-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html
# We will use the host's nginx to serve, but this image is good for testing or isolated deploy
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
