"""
Mahameru Terminal — Global Model Registry (Backend)
Central source of truth for all LLM models available across the platform.
"""

import os
from dotenv import load_dotenv
load_dotenv()

MODEL_PROVIDERS = {
    "DEEPSEEK": "DeepSeek",
    "GOOGLE": "Google",
    "OPENAI": "OpenAI",
    "MOONSHOT": "Moonshot AI",
    "MINIMAX": "Minimax",
    "ANTHROPIC": "Anthropic",
    "META": "Meta",
    "OPENROUTER": "OpenRouter",
    "DIT": "DIT.ai",
    "OSIRIS": "Osiris Code",
}

AVAILABLE_MODELS = [
    # === GRATIS (FREE) TIERS ===
    {
        "id": "openai/gpt-oss-120b:free",
        "name": "GPT OSS 120B (Free)",
        "provider": MODEL_PROVIDERS["OPENROUTER"],
        "base_url": "https://openrouter.ai/api/v1",
        "api_key_env": "OPENROUTER_API_KEY",
    },
    {
        "id": "openai/gpt-oss-20b:free",
        "name": "GPT OSS 20B (Free)",
        "provider": MODEL_PROVIDERS["OPENROUTER"],
        "base_url": "https://openrouter.ai/api/v1",
        "api_key_env": "OPENROUTER_API_KEY",
    },
    {
        "id": "google/gemma-3-27b-it:free",
        "name": "Gemma 3 27B (Free)",
        "provider": MODEL_PROVIDERS["OPENROUTER"],
        "base_url": "https://openrouter.ai/api/v1",
        "api_key_env": "OPENROUTER_API_KEY",
    },
    {
        "id": "google/gemma-3-12b-it:free",
        "name": "Gemma 3 12B (Free)",
        "provider": MODEL_PROVIDERS["OPENROUTER"],
        "base_url": "https://openrouter.ai/api/v1",
        "api_key_env": "OPENROUTER_API_KEY",
    },
    {
        "id": "meta-llama/llama-3.3-70b-instruct:free",
        "name": "Llama 3.3 70B (Free)",
        "provider": MODEL_PROVIDERS["OPENROUTER"],
        "base_url": "https://openrouter.ai/api/v1",
        "api_key_env": "OPENROUTER_API_KEY",
    },
    {
        "id": "meta-llama/llama-3.2-3b-instruct:free",
        "name": "Llama 3.2 3B (Free)",
        "provider": MODEL_PROVIDERS["OPENROUTER"],
        "base_url": "https://openrouter.ai/api/v1",
        "api_key_env": "OPENROUTER_API_KEY",
    },
    {
        "id": "nvidia/nemotron-3-super-120b-a12b:free",
        "name": "Nemotron 3 Super (Free)",
        "provider": MODEL_PROVIDERS["OPENROUTER"],
        "base_url": "https://openrouter.ai/api/v1",
        "api_key_env": "OPENROUTER_API_KEY",
    },
    {
        "id": "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free",
        "name": "Nemotron 3 Nano Omni (Free)",
        "provider": MODEL_PROVIDERS["OPENROUTER"],
        "base_url": "https://openrouter.ai/api/v1",
        "api_key_env": "OPENROUTER_API_KEY",
    },
    {
        "id": "nvidia/nemotron-3-nano-30b-a3b:free",
        "name": "Nemotron 3 Nano 30B (Free)",
        "provider": MODEL_PROVIDERS["OPENROUTER"],
        "base_url": "https://openrouter.ai/api/v1",
        "api_key_env": "OPENROUTER_API_KEY",
    },
    {
        "id": "nvidia/nemotron-nano-12b-v2-vl:free",
        "name": "Nemotron Nano 12B VL (Free)",
        "provider": MODEL_PROVIDERS["OPENROUTER"],
        "base_url": "https://openrouter.ai/api/v1",
        "api_key_env": "OPENROUTER_API_KEY",
    },
    {
        "id": "nvidia/nemotron-nano-9b-v2:free",
        "name": "Nemotron Nano 9B V2 (Free)",
        "provider": MODEL_PROVIDERS["OPENROUTER"],
        "base_url": "https://openrouter.ai/api/v1",
        "api_key_env": "OPENROUTER_API_KEY",
    },
    {
        "id": "qwen/qwen3-coder-480b-a35b-instruct:free",
        "name": "Qwen 3 Coder (Free)",
        "provider": MODEL_PROVIDERS["OPENROUTER"],
        "base_url": "https://openrouter.ai/api/v1",
        "api_key_env": "OPENROUTER_API_KEY",
    },
    {
        "id": "qwen/qwen3-next-80b-a35b-instruct:free",
        "name": "Qwen 3 Next 80B (Free)",
        "provider": MODEL_PROVIDERS["OPENROUTER"],
        "base_url": "https://openrouter.ai/api/v1",
        "api_key_env": "OPENROUTER_API_KEY",
    },
    {
        "id": "z-ai/glm-4.5-air:free",
        "name": "GLM 4.5 Air (Free)",
        "provider": MODEL_PROVIDERS["OPENROUTER"],
        "base_url": "https://openrouter.ai/api/v1",
        "api_key_env": "OPENROUTER_API_KEY",
    },
    {
        "id": "nousresearch/hermes-3-405b:free",
        "name": "Hermes 3 405B (Free)",
        "provider": MODEL_PROVIDERS["OPENROUTER"],
        "base_url": "https://openrouter.ai/api/v1",
        "api_key_env": "OPENROUTER_API_KEY",
    },
    {
        "id": "deepseek/deepseek-r1:free",
        "name": "DeepSeek R1 (Router Free)",
        "provider": MODEL_PROVIDERS["OPENROUTER"],
        "base_url": "https://openrouter.ai/api/v1",
        "api_key_env": "OPENROUTER_API_KEY",
    },

    # === MURAH (ECONOMY) TIERS ===
    {
        "id": "minimax-m2.5",
        "name": "Minimax M2.5",
        "provider": MODEL_PROVIDERS["DIT"],
        "base_url": "https://api.dit.ai/v1",
        "api_key_env": "DIT_API_KEY",
    },
    {
        "id": "minimax-m2.7",
        "name": "Minimax M2.7",
        "provider": MODEL_PROVIDERS["DIT"],
        "base_url": "https://api.dit.ai/v1",
        "api_key_env": "DIT_API_KEY",
    },
    {
        "id": "deepseek-v4-flash",
        "name": "DeepSeek V4 Flash",
        "provider": MODEL_PROVIDERS["DEEPSEEK"],
        "base_url": "https://api.deepseek.com/v1",
        "api_key_env": "DEEPSEEK_API_KEY",
    },
    {
        "id": "gemini-3-flash-preview",
        "name": "Gemini 3 Flash Preview",
        "provider": MODEL_PROVIDERS["DIT"],
        "base_url": "https://api.dit.ai/v1",
        "api_key_env": "DIT_API_KEY",
    },
    {
        "id": "kimi-k2.5",
        "name": "Kimi k2.5",
        "provider": MODEL_PROVIDERS["DIT"],
        "base_url": "https://api.dit.ai/v1",
        "api_key_env": "DIT_API_KEY",
    },
    {
        "id": "gpt-5.4-mini",
        "name": "GPT 5.4 Mini",
        "provider": MODEL_PROVIDERS["DIT"],
        "base_url": "https://api.dit.ai/v1",
        "api_key_env": "DIT_API_KEY",
    },
    {
        "id": "claude-haiku-4-5-20251001",
        "name": "Claude 4.5 Haiku",
        "provider": MODEL_PROVIDERS["DIT"],
        "base_url": "https://api.dit.ai/v1",
        "api_key_env": "DIT_API_KEY",
    },
    {
        "id": "gemini-3.1-flash-image-preview",
        "name": "Gemini 3.1 Flash Image",
        "provider": MODEL_PROVIDERS["DIT"],
        "base_url": "https://api.dit.ai/v1",
        "api_key_env": "DIT_API_KEY",
    },

    # === PRO (PROFESSIONAL) TIERS ===
    {
        "id": "gpt-5.1",
        "name": "GPT 5.1",
        "provider": MODEL_PROVIDERS["DIT"],
        "base_url": "https://api.dit.ai/v1",
        "api_key_env": "DIT_API_KEY",
    },
    {
        "id": "deepseek-chat",
        "name": "DeepSeek Chat",
        "provider": MODEL_PROVIDERS["DEEPSEEK"],
        "base_url": "https://api.deepseek.com/v1",
        "api_key_env": "DEEPSEEK_API_KEY",
    },
    {
        "id": "gemini-3-pro-preview",
        "name": "Gemini 3 Pro Preview",
        "provider": MODEL_PROVIDERS["DIT"],
        "base_url": "https://api.dit.ai/v1",
        "api_key_env": "DIT_API_KEY",
    },
    {
        "id": "gemini-3.1-pro-preview",
        "name": "Gemini 3.1 Pro Preview",
        "provider": MODEL_PROVIDERS["DIT"],
        "base_url": "https://api.dit.ai/v1",
        "api_key_env": "DIT_API_KEY",
    },
    {
        "id": "gpt-5.2",
        "name": "GPT 5.2",
        "provider": MODEL_PROVIDERS["DIT"],
        "base_url": "https://api.dit.ai/v1",
        "api_key_env": "DIT_API_KEY",
    },
    {
        "id": "gpt-5.4",
        "name": "GPT 5.4",
        "provider": MODEL_PROVIDERS["DIT"],
        "base_url": "https://api.dit.ai/v1",
        "api_key_env": "DIT_API_KEY",
    },
    {
        "id": "claude-sonnet-4-6",
        "name": "Claude 4.6 Sonnet",
        "provider": MODEL_PROVIDERS["DIT"],
        "base_url": "https://api.dit.ai/v1",
        "api_key_env": "DIT_API_KEY",
    },
    {
        "id": "claude-sonnet-4-5-20250929",
        "name": "Claude 4.5 Sonnet",
        "provider": MODEL_PROVIDERS["DIT"],
        "base_url": "https://api.dit.ai/v1",
        "api_key_env": "DIT_API_KEY",
    },
    {
        "id": "deepseek-v4-pro",
        "name": "DeepSeek V4 Pro",
        "provider": MODEL_PROVIDERS["DEEPSEEK"],
        "base_url": "https://api.deepseek.com/v1",
        "api_key_env": "DEEPSEEK_API_KEY",
    },

    # === PREMIUM (INSTITUTIONAL) TIERS ===
    {
        "id": "claude-opus-4-6",
        "name": "Claude 4.6 Opus",
        "provider": MODEL_PROVIDERS["DIT"],
        "base_url": "https://api.dit.ai/v1",
        "api_key_env": "DIT_API_KEY",
    },
    {
        "id": "claude-opus-4-5-20251101",
        "name": "Claude 4.5 Opus",
        "provider": MODEL_PROVIDERS["DIT"],
        "base_url": "https://api.dit.ai/v1",
        "api_key_env": "DIT_API_KEY",
    },
    {
        "id": "claude-opus-4-7",
        "name": "Claude 4.7 Opus",
        "provider": MODEL_PROVIDERS["DIT"],
        "base_url": "https://api.dit.ai/v1",
        "api_key_env": "DIT_API_KEY",
    },
    {
        "id": "deepseek-reasoner",
        "name": "DeepSeek Reasoner (R1)",
        "provider": MODEL_PROVIDERS["DEEPSEEK"],
        "base_url": "https://api.deepseek.com/v1",
        "api_key_env": "DEEPSEEK_API_KEY",
    },
    {
        "id": "deepseek-r1",
        "name": "DeepSeek R1",
        "provider": MODEL_PROVIDERS["DEEPSEEK"],
        "base_url": "https://api.deepseek.com/v1",
        "api_key_env": "DEEPSEEK_API_KEY",
    },
    {
        "id": "gpt-5.5",
        "name": "GPT 5.5",
        "provider": MODEL_PROVIDERS["DIT"],
        "base_url": "https://api.dit.ai/v1",
        "api_key_env": "DIT_API_KEY",
    },
    {
        "id": "gpt-image-2",
        "name": "DIT Image Gen v2",
        "provider": MODEL_PROVIDERS["DIT"],
        "base_url": "https://api.dit.ai/v1",
        "api_key_env": "DIT_API_KEY",
    },
    # === OSIRIS CODE TIERS ===
    {
        "id": "claude-opus-4-6:osiris",
        "name": "Claude 4.6 Opus (Osiris)",
        "provider": MODEL_PROVIDERS["OSIRIS"],
        "base_url": os.getenv("OSIRIS_BASE_URL", "https://ai.osiris-code.com/v1"),
        "api_key_env": "OSIRIS_API_KEY",
    },
    {
        "id": "claude-sonnet-4-5:osiris",
        "name": "Claude 4.5 Sonnet (Osiris)",
        "provider": MODEL_PROVIDERS["OSIRIS"],
        "base_url": os.getenv("OSIRIS_BASE_URL", "https://ai.osiris-code.com/v1"),
        "api_key_env": "OSIRIS_API_KEY",
    },
    {
        "id": "gpt-5-4:osiris",
        "name": "Codex GPT 5.4 (Osiris)",
        "provider": MODEL_PROVIDERS["OSIRIS"],
        "base_url": os.getenv("OSIRIS_BASE_URL", "https://ai.osiris-code.com/v1"),
        "api_key_env": "OSIRIS_API_KEY",
    },
    {
        "id": "gpt-5-5:osiris",
        "name": "Codex GPT 5.5 (Osiris)",
        "provider": MODEL_PROVIDERS["OSIRIS"],
        "base_url": os.getenv("OSIRIS_BASE_URL", "https://ai.osiris-code.com/v1"),
        "api_key_env": "OSIRIS_API_KEY",
    },
    {
        "id": "deepseek-v4-pro:osiris",
        "name": "DeepSeek V4 Pro (Osiris)",
        "provider": MODEL_PROVIDERS["OSIRIS"],
        "base_url": os.getenv("OSIRIS_BASE_URL", "https://ai.osiris-code.com/v1"),
        "api_key_env": "OSIRIS_API_KEY",
    },
    {
        "id": "gemini-3-1-pro:osiris",
        "name": "Gemini 3.1 Pro (Osiris)",
        "provider": MODEL_PROVIDERS["OSIRIS"],
        "base_url": os.getenv("OSIRIS_BASE_URL", "https://ai.osiris-code.com/v1"),
        "api_key_env": "OSIRIS_API_KEY",
    },
    {
        "id": "glm-5.1:osiris",
        "name": "GLM 5.1 (Osiris)",
        "provider": MODEL_PROVIDERS["OSIRIS"],
        "base_url": os.getenv("OSIRIS_BASE_URL", "https://ai.osiris-code.com/v1"),
        "api_key_env": "OSIRIS_API_KEY",
    },
    {
        "id": "glm-5v-turbo:osiris",
        "name": "GLM 5V Turbo (Osiris)",
        "provider": MODEL_PROVIDERS["OSIRIS"],
        "base_url": os.getenv("OSIRIS_BASE_URL", "https://ai.osiris-code.com/v1"),
        "api_key_env": "OSIRIS_API_KEY",
    },
    {
        "id": "kimi-k2.6:osiris",
        "name": "Kimi K2.6 (Osiris)",
        "provider": MODEL_PROVIDERS["OSIRIS"],
        "base_url": os.getenv("OSIRIS_BASE_URL", "https://ai.osiris-code.com/v1"),
        "api_key_env": "OSIRIS_API_KEY",
    },
]

DEFAULT_MODEL_ID = "deepseek-v4-flash"
